spring:
    jpa:
        database: MYSQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        driver-class-name: com.mysql.jdbc.Driver
        continue-on-error: true

